const test=require('node:test'),assert=require('node:assert/strict');
const {validateBooking}=require('../lib/rules');const {adminRanges,monthBounds}=require('../lib/admin-rules');const {isAdmin,requireAdmin}=require('../lib/admin');const auth=require('../lib/auth');
const now=Date.parse('2026-10-05T08:00:00+09:00');const base={date:'2026-10-06',room:'A',start:'09:00',termsAccepted:true};
const response=()=>({setHeader(){},status(n){this.code=n;return this;},json(v){this.body=v;return this;}});
test('continuous frames include gaps and charge full usage duration',()=>{const v=validateBooking({...base,hours:3},now);assert.equal(v.end,'14:00');assert.deepEqual(v.ranges,[{date:base.date,room:'A',start:'09:00',end:'14:00'}]);assert.equal(v.price,6000);assert.equal(validateBooking({...base,hours:7},now).end,'22:00');for(const hours of [0,8,1.5,'3'])assert.ok(validateBooking({...base,hours},now).error);assert.ok(validateBooking({...base,start:'21:00',hours:2},now).error);});
test('admin batch merges adjacent frames only within the same date',()=>{const b={month:'2026-10',room:'B',slots:[{date:'2026-10-07',start:'09:00'},{date:'2026-10-06',start:'13:00'},{date:'2026-10-06',start:'09:00'},{date:'2026-10-06',start:'11:00'}]};const v=adminRanges(b,now);assert.equal(v.ranges.length,2);assert.equal(v.ranges[0].end,'14:00');assert.equal(v.price,7200);assert.ok(adminRanges({...b,slots:[b.slots[0],b.slots[0]]},now).error);assert.ok(adminRanges({...b,month:'2026-11'},now).error);assert.equal(monthBounds('2026-12').next,'2027-01-01');assert.equal(monthBounds('2026-13'),null);});
test('admin privilege binds exact member ID and email, denies absent config',async()=>{process.env.ADMIN_USER_ID='88';process.env.ADMIN_EMAIL='owner@example.invalid';assert.equal(isAdmin({id:'88',email:'owner@example.invalid'}),true);assert.equal(isAdmin({id:'89',email:'owner@example.invalid'}),false);assert.equal(isAdmin({id:'88',email:'other@example.invalid'}),false);process.env.AUTH_SECRET='a'.repeat(64);let cookie;auth.setSession({setHeader:(k,v)=>cookie=v},'89');const res=response();await requireAdmin({headers:{cookie}},res,async()=>[{id:'89',email:'owner@example.invalid'}]);assert.equal(res.code,403);delete process.env.ADMIN_USER_ID;assert.equal(isAdmin({id:'88',email:'owner@example.invalid'}),false);});
test('new mutation endpoints reject anonymous and cross-origin requests',async()=>{for(const file of ['../api/cancel','../api/admin/bookings']){const handler=require(file);let r=response();await handler({method:'POST',headers:{'content-type':'application/json',host:'studio.test'},body:{id:1}},r);assert.equal(r.statusCode,401);r=response();await handler({method:'POST',headers:{'content-type':'application/json',host:'studio.test',origin:'https://other.test'},body:{id:1}},r);assert.equal(r.code,403);}});

test('session cannot cross deployment or public host',()=>{process.env.AUTH_SECRET='a'.repeat(64);let cookie;auth.setSession({setHeader:(k,v)=>cookie=v},'88',{headers:{host:'136s.vercel.app'}});assert.equal(auth.userId({headers:{cookie,host:'136s.vercel.app'}}),'88');assert.equal(auth.userId({headers:{cookie,host:'preview.vercel.app'}}),null);});

test('calendar month booking windows include deadline and clamp month end',()=>{const {bookingDeadline}=require('../lib/rules');assert.equal(bookingDeadline('2026-01-31',1),'2026-02-28');assert.equal(bookingDeadline('2028-01-31',1),'2028-02-29');assert.equal(bookingDeadline('2026-11-30',3),'2027-02-28');assert.ok(!validateBooking({...base,date:'2026-11-05'},now).error);assert.ok(validateBooking({...base,date:'2026-11-06'},now).error);assert.ok(!adminRanges({month:'2027-01',room:'A',slots:[{date:'2027-01-05',start:'09:00'}]},now).error);assert.ok(adminRanges({month:'2027-01',room:'A',slots:[{date:'2027-01-06',start:'09:00'}]},now).error);});

test('multiple administrators bind each ID and email and preserve original owner',()=>{process.env.ADMIN_USER_ID='25';process.env.ADMIN_EMAIL='owner@example.invalid';process.env.ADMIN_ACCOUNTS=JSON.stringify([{id:'26',email:'second@example.invalid'}]);assert.equal(isAdmin({id:25,email:'owner@example.invalid'}),true);assert.equal(isAdmin({id:26,email:'second@example.invalid'}),true);assert.equal(isAdmin({id:27,email:'second@example.invalid'}),false);assert.equal(isAdmin({id:26,email:'owner@example.invalid'}),false);process.env.ADMIN_ACCOUNTS='invalid';assert.equal(isAdmin({id:26,email:'second@example.invalid'}),false);assert.equal(isAdmin(null),false);delete process.env.ADMIN_ACCOUNTS;});


test('admin separates dates and non-adjacent selections for prices',()=>{const slots=[{date:'2026-10-06',start:'09:00'},{date:'2026-10-06',start:'11:00'},{date:'2026-10-06',start:'15:00'},{date:'2026-10-07',start:'21:00'}];const v=adminRanges({month:'2026-10',room:'A',slots},now);assert.equal(v.ranges.length,3);assert.equal(v.price,6000);assert.equal(v.ranges[0].end,'12:00');assert.equal(v.ranges.at(-1).end,'22:00');});
